### ISSUE TITLE
Disable cloudstitch manual upload button during upload

### ISSUE THREAD

**Issue by yusufm** [Labsmore/pyuscope#163]
When someone clicks the manual upload button on cloudstitch app there is no indication that a upload has started. 

We should at least disable the button while an upload is happening. 

This whole flow/option could use some UX rework.

**Comment by JohnDMcMaster** [comment]
Currently uploads queue which is not unreasonable behavior. Maybe though we can detect a duplicate upload and ignore the second request?

**Comment by JohnDMcMaster** [comment]
Code changed to print a warning and ignore the upload if its a duplicate of the last upload

**Comment by JohnDMcMaster** [comment]
I'm going to assume this is good enough for the intended issue. Please re-open if you want to see something different
