### ISSUE TITLE
joystick: provide a way for user to adjust sensitivity

### ISSUE THREAD

**Issue by JohnDMcMaster** [Labsmore/pyuscope#288]
Maybe sliders in the GUI? something you can set and then save

**Comment by nsfm** [comment]
Not sure what kind of joystick you are working with, and this use case is probably not the most relevant, but maybe you will find this interesting...

I was working on a similar project last year, using a microscope rigged up to a Marlin CNC device with a PS5 dualsense controller. For my project I need to constantly alternate between fast jogging to locate objects and fine movement to manipulate them. Ultimately I factored the analog trigger positions into the top speed, with the right trigger acting like an accelerator and the left trigger acting as a brake. Full pull on the right trigger multiplied velocity by up to 80x, and the left divided it by up to 80x. Felt really natural, lots of fun too. 

Just wanted to share the thought. This project is awesome, looking forward to keeping up with it 😄
