### ISSUE TITLE
Use TOML for configuration

### ISSUE THREAD

**Issue by FFY00** [Labsmore/pyuscope#30]
IMO, TOML provides a much nicer configuration language than JSON, which would help make this project just a little bit more user friendly.

TOML mappings are really close to JSON mappings, I am pretty sure we don't need to any custom logic. The API is the same, we should be able to just use `toml` module instead of `json` for TOML configs.

The Python packaging scene is also moving to TOML as a configuration language, see [PEP518](https://www.python.org/dev/peps/pep-0518/), so it's more than likely that the dependency is already met for most users.

https://github.com/toml-lang/toml

https://github.com/uiri/toml#api-reference

This is just a sugestion :blush:

**Comment by JohnDMcMaster** [comment]
Will take a look. Priority right now though will probably go to other areas

**Comment by JohnDMcMaster** [comment]
Thanks for the feedback but after careful consideration we've decided to move to JSON5. This was mostly due to JSON to JSON5 being a trivial transition to fix our pain points but its was less clear if TOML would offer any significant advantages over JSON5 for our use case.
