### ISSUE TITLE
Crash when hitting stop on main

### ISSUE THREAD

**Issue by yusufm** [Labsmore/pyuscope#339]
![image](https://github.com/Labsmore/pyuscope/assets/463376/8987f4cf-b902-471e-a02c-b4a94e5f6550)
See this error, happened when hitting stop on an ongoing scan rigth after it was started.

**Comment by JohnDMcMaster** [comment]
I haven't tested this but there was an "obvious" bug I've pushed a fix for

**Comment by JohnDMcMaster** [comment]
I was using stop recently (after above patch) and it seemed fine. Closing as should be fixed
