### ISSUE TITLE
No indication limits are being hit in the gui

### ISSUE THREAD

**Issue by yusufm** [Labsmore/pyuscope#80]
I see the following in the terminal:

![image](https://user-images.githubusercontent.com/463376/211700130-519a2718-6fe9-433e-a5fa-570db31d3b7d.jpeg)

But no indication in the gui that it's not moving because of limits reached:

![image](https://user-images.githubusercontent.com/463376/211700231-c0e6fdd9-5e3e-47b9-8283-b0ffa1b74573.jpeg)

**Comment by JohnDMcMaster** [comment]
you get log messages now
